//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AudioPlayUtilWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("AudioPlayUtil");
		L.RegFunction("Create", Create);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Create(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.AudioSource arg0 = (UnityEngine.AudioSource)ToLua.CheckObject(L, 1, typeof(UnityEngine.AudioSource));
			UnityEngine.AudioClip arg1 = (UnityEngine.AudioClip)ToLua.CheckObject(L, 2, typeof(UnityEngine.AudioClip));
			float arg2 = (float)LuaDLL.luaL_checknumber(L, 3);
			AudioPlayOperation o = AudioPlayUtil.Create(arg0, arg1, arg2);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

