//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ComponentCache_QuickGrid_InjectionWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ComponentCache.QuickGrid_Injection), typeof(ComponentCache.Injection<littlerbird.UI.QuickGrid>));
		L.RegFunction("New", _CreateComponentCache_QuickGrid_Injection);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateComponentCache_QuickGrid_Injection(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ComponentCache.QuickGrid_Injection obj = new ComponentCache.QuickGrid_Injection();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ComponentCache.QuickGrid_Injection.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

