//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class littlerbird_UI_QuickGridItemBaseWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(littlerbird.UI.QuickGridItemBase), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("Init", Init);
		L.RegFunction("OnPointerClick", OnPointerClick);
		L.RegFunction("OnItemTweenComplete", OnItemTweenComplete);
		L.RegFunction("OnAllTweenComplete", OnAllTweenComplete);
		L.RegFunction("OnDataChange", OnDataChange);
		L.RegFunction("OnSelectChange", OnSelectChange);
		L.RegFunction("OnItemClick", OnItemClick);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("config", get_config, set_config);
		L.RegVar("index", get_index, set_index);
		L.RegVar("line", get_line, set_line);
		L.RegVar("data", get_data, set_data);
		L.RegVar("selected", get_selected, null);
		L.RegVar("localTsf", get_localTsf, null);
		L.RegVar("localGo", get_localGo, null);
		L.RegVar("itemName", get_itemName, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			littlerbird.UI.QuickGridItemBase obj = (littlerbird.UI.QuickGridItemBase)ToLua.CheckObject<littlerbird.UI.QuickGridItemBase>(L, 1);
			obj.Init();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPointerClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			littlerbird.UI.QuickGridItemBase obj = (littlerbird.UI.QuickGridItemBase)ToLua.CheckObject<littlerbird.UI.QuickGridItemBase>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnPointerClick(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnItemTweenComplete(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			littlerbird.UI.QuickGridItemBase obj = (littlerbird.UI.QuickGridItemBase)ToLua.CheckObject<littlerbird.UI.QuickGridItemBase>(L, 1);
			obj.OnItemTweenComplete();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnAllTweenComplete(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			littlerbird.UI.QuickGridItemBase obj = (littlerbird.UI.QuickGridItemBase)ToLua.CheckObject<littlerbird.UI.QuickGridItemBase>(L, 1);
			obj.OnAllTweenComplete();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDataChange(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			littlerbird.UI.QuickGridItemBase obj = (littlerbird.UI.QuickGridItemBase)ToLua.CheckObject<littlerbird.UI.QuickGridItemBase>(L, 1);
			obj.OnDataChange();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnSelectChange(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			littlerbird.UI.QuickGridItemBase obj = (littlerbird.UI.QuickGridItemBase)ToLua.CheckObject<littlerbird.UI.QuickGridItemBase>(L, 1);
			obj.OnSelectChange();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnItemClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			littlerbird.UI.QuickGridItemBase obj = (littlerbird.UI.QuickGridItemBase)ToLua.CheckObject<littlerbird.UI.QuickGridItemBase>(L, 1);
			obj.OnItemClick();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_config(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			littlerbird.UI.QuickGridItemBase obj = (littlerbird.UI.QuickGridItemBase)o;
			littlerbird.UI.QuickGrid ret = obj.config;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index config on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_index(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			littlerbird.UI.QuickGridItemBase obj = (littlerbird.UI.QuickGridItemBase)o;
			int ret = obj.index;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index index on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_line(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			littlerbird.UI.QuickGridItemBase obj = (littlerbird.UI.QuickGridItemBase)o;
			int ret = obj.line;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index line on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_data(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			littlerbird.UI.QuickGridItemBase obj = (littlerbird.UI.QuickGridItemBase)o;
			object ret = obj.data;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index data on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_selected(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			littlerbird.UI.QuickGridItemBase obj = (littlerbird.UI.QuickGridItemBase)o;
			bool ret = obj.selected;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index selected on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_localTsf(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			littlerbird.UI.QuickGridItemBase obj = (littlerbird.UI.QuickGridItemBase)o;
			UnityEngine.Transform ret = obj.localTsf;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index localTsf on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_localGo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			littlerbird.UI.QuickGridItemBase obj = (littlerbird.UI.QuickGridItemBase)o;
			UnityEngine.GameObject ret = obj.localGo;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index localGo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_itemName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			littlerbird.UI.QuickGridItemBase obj = (littlerbird.UI.QuickGridItemBase)o;
			string ret = obj.itemName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index itemName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_config(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			littlerbird.UI.QuickGridItemBase obj = (littlerbird.UI.QuickGridItemBase)o;
			littlerbird.UI.QuickGrid arg0 = (littlerbird.UI.QuickGrid)ToLua.CheckObject<littlerbird.UI.QuickGrid>(L, 2);
			obj.config = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index config on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_index(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			littlerbird.UI.QuickGridItemBase obj = (littlerbird.UI.QuickGridItemBase)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.index = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index index on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_line(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			littlerbird.UI.QuickGridItemBase obj = (littlerbird.UI.QuickGridItemBase)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.line = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index line on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_data(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			littlerbird.UI.QuickGridItemBase obj = (littlerbird.UI.QuickGridItemBase)o;
			object arg0 = ToLua.ToVarObject(L, 2);
			obj.data = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index data on a nil value");
		}
	}
}

