//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SmartTimerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SmartTimer), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("Subscribe", Subscribe);
		L.RegFunction("SingleSet", SingleSet);
		L.RegFunction("Kill", Kill);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("instance", get_instance, null);
		L.RegVar("serverTimeDiff", get_serverTimeDiff, set_serverTimeDiff);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Subscribe(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			SmartTimer obj = (SmartTimer)ToLua.CheckObject<SmartTimer>(L, 1);
			double arg0 = (double)LuaDLL.luaL_checknumber(L, 2);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
			int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
			TimeEvent o = obj.Subscribe(arg0, arg1, arg2);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SingleSet(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SmartTimer obj = (SmartTimer)ToLua.CheckObject<SmartTimer>(L, 1);
			TimeEvent arg0 = (TimeEvent)ToLua.CheckObject<TimeEvent>(L, 2);
			TimeEvent o = obj.SingleSet(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Kill(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SmartTimer obj = (SmartTimer)ToLua.CheckObject<SmartTimer>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.Kill(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_instance(IntPtr L)
	{
		try
		{
			ToLua.Push(L, SmartTimer.instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_serverTimeDiff(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SmartTimer obj = (SmartTimer)o;
			long ret = obj.serverTimeDiff;
			LuaDLL.tolua_pushint64(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index serverTimeDiff on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_serverTimeDiff(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SmartTimer obj = (SmartTimer)o;
			long arg0 = LuaDLL.tolua_checkint64(L, 2);
			obj.serverTimeDiff = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index serverTimeDiff on a nil value");
		}
	}
}

