//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_Events_UnityEvent_LoopBaseNodeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.Events.UnityEvent<LoopBaseNode>), typeof(UnityEngine.Events.UnityEventBase), "UnityEvent_LoopBaseNode");
		L.RegFunction("AddListener", AddListener);
		L.RegFunction("RemoveListener", RemoveListener);
		L.RegFunction("Invoke", Invoke);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Events.UnityEvent<LoopBaseNode> obj = (UnityEngine.Events.UnityEvent<LoopBaseNode>)ToLua.CheckObject<UnityEngine.Events.UnityEvent<LoopBaseNode>>(L, 1);
			UnityEngine.Events.UnityAction<LoopBaseNode> arg0 = (UnityEngine.Events.UnityAction<LoopBaseNode>)ToLua.CheckDelegate<UnityEngine.Events.UnityAction<LoopBaseNode>>(L, 2);
			obj.AddListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Events.UnityEvent<LoopBaseNode> obj = (UnityEngine.Events.UnityEvent<LoopBaseNode>)ToLua.CheckObject<UnityEngine.Events.UnityEvent<LoopBaseNode>>(L, 1);
			UnityEngine.Events.UnityAction<LoopBaseNode> arg0 = (UnityEngine.Events.UnityAction<LoopBaseNode>)ToLua.CheckDelegate<UnityEngine.Events.UnityAction<LoopBaseNode>>(L, 2);
			obj.RemoveListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Invoke(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Events.UnityEvent<LoopBaseNode> obj = (UnityEngine.Events.UnityEvent<LoopBaseNode>)ToLua.CheckObject<UnityEngine.Events.UnityEvent<LoopBaseNode>>(L, 1);
			LoopBaseNode arg0 = (LoopBaseNode)ToLua.CheckObject<LoopBaseNode>(L, 2);
			obj.Invoke(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

