C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\baibazhang\table  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\baibazhang\table C:\UnityProject\DaHuGame\Public\probuff\baibazhang\table\room.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\bullfight  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\bullfight C:\UnityProject\DaHuGame\Public\probuff\bullfight\login.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\bullfight\bijitable  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\bullfight\bijitable C:\UnityProject\DaHuGame\Public\probuff\bullfight\bijitable\room.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\bullfight\table  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\bullfight\table C:\UnityProject\DaHuGame\Public\probuff\bullfight\table\game.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\bullfight\table  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\bullfight\table C:\UnityProject\DaHuGame\Public\probuff\bullfight\table\login.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\bullfight\table  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\bullfight\table C:\UnityProject\DaHuGame\Public\probuff\bullfight\table\room.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\cowboy  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\cowboy C:\UnityProject\DaHuGame\Public\probuff\cowboy\login.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\cowboy\table  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\cowboy\table C:\UnityProject\DaHuGame\Public\probuff\cowboy\table\game.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\cowboy\table  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\cowboy\table C:\UnityProject\DaHuGame\Public\probuff\cowboy\table\login.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\cowboy\table  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\cowboy\table C:\UnityProject\DaHuGame\Public\probuff\cowboy\table\room.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\daigoutui\table  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\daigoutui\table C:\UnityProject\DaHuGame\Public\probuff\daigoutui\table\game.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\doudizhu\table  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\doudizhu\table C:\UnityProject\DaHuGame\Public\probuff\doudizhu\table\game.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\guandan  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\guandan C:\UnityProject\DaHuGame\Public\probuff\guandan\login.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\guandan\table  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\guandan\table C:\UnityProject\DaHuGame\Public\probuff\guandan\table\game_guandan.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\guandan\table  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\guandan\table C:\UnityProject\DaHuGame\Public\probuff\guandan\table\login.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\guandan\table  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\guandan\table C:\UnityProject\DaHuGame\Public\probuff\guandan\table\room.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\henanmj  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\henanmj C:\UnityProject\DaHuGame\Public\probuff\henanmj\Game.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\henanmj  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\henanmj C:\UnityProject\DaHuGame\Public\probuff\henanmj\GameFrame.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\henanmj  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\henanmj C:\UnityProject\DaHuGame\Public\probuff\henanmj\Login.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\laoyancai\table  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\laoyancai\table C:\UnityProject\DaHuGame\Public\probuff\laoyancai\table\game.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\paohuzi  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\paohuzi C:\UnityProject\DaHuGame\Public\probuff\paohuzi\GameCommon.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\paohuzi  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\paohuzi C:\UnityProject\DaHuGame\Public\probuff\paohuzi\GamePaoHuZi.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\public  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\public C:\UnityProject\DaHuGame\Public\probuff\public\login.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\public\skynet_table  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\public\skynet_table C:\UnityProject\DaHuGame\Public\probuff\public\skynet_table\login.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\public\skynet_table  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\public\skynet_table C:\UnityProject\DaHuGame\Public\probuff\public\skynet_table\room.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\runfast  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\runfast C:\UnityProject\DaHuGame\Public\probuff\runfast\login.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\runfast\mytable  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\runfast\mytable C:\UnityProject\DaHuGame\Public\probuff\runfast\mytable\controller.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\runfast\mytable  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\runfast\mytable C:\UnityProject\DaHuGame\Public\probuff\runfast\mytable\game.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\runfast\table  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\runfast\table C:\UnityProject\DaHuGame\Public\probuff\runfast\table\game.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\runfast\table  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\runfast\table C:\UnityProject\DaHuGame\Public\probuff\runfast\table\login.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\runfast\table  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\runfast\table C:\UnityProject\DaHuGame\Public\probuff\runfast\table\room.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\sangong\table  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\sangong\table C:\UnityProject\DaHuGame\Public\probuff\sangong\table\game.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\shisanzhang\table  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\shisanzhang\table C:\UnityProject\DaHuGame\Public\probuff\shisanzhang\table\room.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\zhajinhua\mytable  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\zhajinhua\mytable C:\UnityProject\DaHuGame\Public\probuff\zhajinhua\mytable\game.proto
C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=C:\UnityProject\DaHuGame\Public\probuff\zhajinhua\mytable  --plugin=protoc-gen-lua="C:\UnityProject\DaHuGame\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=C:\UnityProject\DaHuGame\Public\out_lua_pb\zhajinhua\mytable C:\UnityProject\DaHuGame\Public\probuff\zhajinhua\mytable\room.proto
