---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by houzhen.
--- DateTime: 2018/1/29 17:38
---

local class = require("lib.middleclass")
---@type TableCommonController
local Base = require('package.majiangshanxi.module.tablenew.controller.tablecommon_controller')
---@class TableXueLiuChengHeController
---@field view TableXueLiuChengHeView
---@field module TableMJModule
local TableXueLiuChengHeController = class('tableCommonController', Base)

--- 开始刷新gameState
function TableXueLiuChengHeController:game_state_begin(gameState)
    if(gameState.HuanSanZhang) then
        self.readyHuanSanZ = true
        self.waitHuanSanZ = (#gameState.Player[self.view.mySeat + 1].SanZhang == 0)
    end
    if(gameState.SanZhangType > 0 and self.readyHuanSanZ) then
        self.readyHuanSanZ = false
        self.waitHuanSanZ = false
        self.module:begin_cache_game_state()
        self.view:huan_san_zhang(gameState,
            function ()
                self.module:end_cache_game_state(self.module.gameState)
            end,
            function ()
                self.module:end_cache_game_state(self.module.gameState)
            end)
    end
end

--- 点击
function TableXueLiuChengHeController:on_click(obj, arg)
    if (obj.name == "Button_Huan") then
        self.model:request_huan_sanz(self.view.huanSanZhangPais)
    else
        Base.on_click(self, obj, arg)
    end
end

--- 点击我的手牌
function TableXueLiuChengHeController:click_my_hand_mj(obj)
    if(self.waitHuanSanZ) then
        self.view:click_select(obj)
    else
        Base.click_my_hand_mj(self, obj)
    end
end

return TableXueLiuChengHeController