-- 编辑器自动生成，请勿直接修改！
local playModeConfig = {
    {
        id           = 1,
        name         = "大众玩法",
        isOpen       = true,
        showIndex    = 1,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "十三张",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "十三张",
                gameName     = "SHISANZHANG",
                gameId       = 12,
                isOpen       = false,
                package      = "shisanzhang",
                location     = 1,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "",
                isOpenUrl    = false,
                wanfaType    = "0",
                createName   = "DHGXQP_SHISANZHANG_SSZ",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_极速跑得快",
                hallName     = "跑得快",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 1,
                name         = "跑得快",
                gameName     = "RUNFAST",
                gameId       = 1,
                isOpen       = true,
                package      = "runfast",
                location     = 1,
                showIndex    = 2,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "跑得快",
                isOpenUrl    = false,
                wanfaType    = "2",
                createName   = "DHGXQP_RUNFAST_RUNFAST",
                tips         = "跑得快",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_拼十",
                hallName     = "拼十",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 3,
                name         = "拼十",
                gameName     = "BULLFIGHT",
                gameId       = 4,
                isOpen       = false,
                package      = "cowboy",
                location     = 1,
                showIndex    = 3,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "牛仔",
                isOpenUrl    = false,
                playTypeName = "bullfight",
                wanfaType    = "0|1|2|3",
                createName   = "DHGXQP_BULLFIGHT_BF",
                tips         = "轮流坐庄|随机坐庄|看牌抢庄|炸金牛",
            },
            {
                img          = "HuNan_Main_图标_转转",
                headIcon     = "Main_入口_转转",
                hallName     = "转转麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "转转麻将",
                gameName     = "GXMJZZ",
                gameId       = 6,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 4,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "转转麻将",
                isOpenUrl    = false,
                wanfaType    = "csmj_zhuanzhuan",
                createName   = "DHGXQP_GXMJZZ_ZZ",
                cardTheame   = "1|1|2",
            },
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "Main_入口_红中",
                hallName     = "红中麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "红中麻将",
                gameName     = "HZHZ",
                gameId       = 7,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 5,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "红中",
                isOpenUrl    = false,
                wanfaType    = "dhqp_hongzhong",
                createName   = "DHGXQP_HZHZ_HZ",
                cardTheame   = "0|0|1",
            },
            {
                img          = "Public_Electorate_按钮_图标_通用斗地主",
                headIcon     = "Main_入口_斗地主",
                hallName     = "斗地主",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "斗地主",
                gameName     = "DOUDIZHU",
                gameId       = 8,
                isOpen       = true,
                package      = "doudizhu",
                location     = 1,
                showIndex    = 6,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "斗地主",
                isOpenUrl    = false,
                wanfaType    = "0",
                createName   = "DHGXQP_DOUDIZHU_DOUDIZHU",
                tips         = "斗地主",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "飘三叶",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "飘三叶",
                gameName     = "ZHAJINHUA",
                gameId       = 9,
                isOpen       = false,
                package      = "zhajinhua",
                location     = 1,
                showIndex    = 7,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "飘三叶",
                isOpenUrl    = false,
                wanfaType    = "0",
                createName   = "DHGXQP_ZHAJINHUA_ZHAJINHUA",
                tips         = "飘三叶",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "摆八张",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "摆八张",
                gameName     = "BAIBAZHANG",
                gameId       = 10,
                isOpen       = false,
                package      = "baibazhang",
                location     = 1,
                showIndex    = 8,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "摆八张",
                isOpenUrl    = false,
                wanfaType    = "0",
                createName   = "DHGXQP_BAIBAZHANG_BBZ",
                tips         = "摆八张",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "三公",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "三公",
                gameName     = "SANGONG",
                gameId       = 11,
                isOpen       = false,
                package      = "sangong",
                location     = 1,
                showIndex    = 9,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "",
                isOpenUrl    = false,
                wanfaType    = "1|2",
                createName   = "DHGXQP_SANGONG_SANGONG",
                tips         = "自由下注|自由抢庄",
            }
        },
    },
    {
        id           = 2,
        name         = "北海市",
        isOpen       = true,
        showIndex    = 2,
        playModeList ={
            {
                img          = "Guangxi_Main_图标_推倒胡",
                headIcon     = "",
                hallName     = "北海推倒胡",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "北海推倒胡",
                gameName     = "BHTDH",
                gameId       = 201,
                isOpen       = true,
                package      = "majiang",
                location     = 2,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "推倒胡",
                isOpenUrl    = false,
                wanfaType    = "gxbh_tuidaohu",
                createName   = "DHGXQP_BHTDH_TDH",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 3,
        name         = "柳州市",
        isOpen       = true,
        showIndex    = 3,
        playModeList ={
            {
                img          = "Guangxi_Main_图标_柳州",
                headIcon     = "",
                hallName     = "柳州麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "柳州麻将",
                gameName     = "LZLZ",
                gameId       = 301,
                isOpen       = true,
                package      = "majiang",
                location     = 3,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "红中",
                isOpenUrl    = false,
                wanfaType    = "gxqp_liuzhou",
                createName   = "DHGXQP_LZLZ_LZ",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 4,
        name         = "梧州市",
        isOpen       = true,
        showIndex    = 4,
        playModeList ={
            {
                img          = "Guangxi_Main_图标_梧州",
                headIcon     = "Main_入口_梧州",
                hallName     = "梧州麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "梧州麻将",
                gameName     = "WZWZ",
                gameId       = 401,
                isOpen       = true,
                package      = "majiang",
                location     = 4,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "红中",
                isOpenUrl    = false,
                wanfaType    = "gxwz_wuzhou",
                createName   = "DHGXQP_WZWZ_WZ",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 5,
        name         = "崇左市",
        isOpen       = true,
        showIndex    = 5,
        playModeList ={
            {
                img          = "Guangxi_Main_图标_扶绥",
                headIcon     = "Main_入口_扶绥",
                hallName     = "扶绥麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "扶绥麻将",
                gameName     = "CZFS",
                gameId       = 501,
                isOpen       = true,
                package      = "majiang",
                location     = 5,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "红中",
                isOpenUrl    = false,
                wanfaType    = "gxcz_fusui",
                createName   = "DHGXQP_CZFS_FS",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 6,
        name         = "桂林市",
        isOpen       = true,
        showIndex    = 6,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_字牌通用",
                headIcon     = "Main_入口_样式_01",
                hallName     = "桂林字牌",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "桂林字牌",
                gameName     = "GLZP",
                gameId       = 601,
                isOpen       = true,
                package      = "paohuzi",
                location     = 6,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "红中",
                isOpenUrl    = false,
                wanfaType    = "phz_guangxi_glzp",
                createName   = "DHGXQP_GLZP_GL",
            }
        },
    },
    {
        id           = 7,
        name         = "南宁市",
        isOpen       = true,
        showIndex    = 7,
        playModeList ={
            {
                img          = "Guangxi_Main_图标_南宁",
                headIcon     = "Main_入口_南宁",
                hallName     = "南宁市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "南宁麻将",
                gameName     = "NNNN",
                gameId       = 701,
                isOpen       = true,
                package      = "majiang",
                location     = 7,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "红中",
                isOpenUrl    = false,
                wanfaType    = "gxqp_nanning",
                createName   = "DHGXQP_NNNN_NN",
                cardTheame   = "1|1|2",
            }
        },
    }
}
return playModeConfig
