-- 编辑器自动生成，请勿直接修改！
local playModeConfig = {
    {
        id           = 1,
        name         = "大众玩法",
        isOpen       = true,
        showIndex    = 1,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "Main_入口_红中",
                hallName     = "红中麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "红中麻将",
                gameName     = "HZMJ",
                gameId       = 1,
                isOpen       = false,
                package      = "majiang",
                location     = 1,
                showIndex    = 1,
                color        = 1,
                isOnline     = false,
                isOpenGold   = false,
                coinName     = "红中",
                isOpenUrl    = false,
                wanfaType    = "hzmj_v2",
                createName   = "DHHUBEIQP_HZMJ_HZ",
                cardTheame   = "0|0|1",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_极速跑得快",
                hallName     = "跑得快",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 1,
                name         = "跑得快",
                gameName     = "RUNFAST",
                gameId       = 3,
                isOpen       = true,
                package      = "runfast",
                location     = 1,
                showIndex    = 2,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "跑得快",
                isOpenUrl    = false,
                wanfaType    = "2",
                createName   = "DHHUBEIQP_RUNFAST_RUNFAST",
                tips         = "跑得快",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_拼十",
                hallName     = "拼十",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 3,
                name         = "拼十",
                gameName     = "BULLFIGHT",
                gameId       = 4,
                isOpen       = false,
                package      = "cowboy",
                location     = 1,
                showIndex    = 3,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "牛仔",
                isOpenUrl    = false,
                playTypeName = "bullfight",
                wanfaType    = "0|1|2|3",
                createName   = "DHHUBEIQP_BULLFIGHT_BF",
                tips         = "轮流坐庄|随机坐庄|看牌抢庄|炸金牛",
            },
            {
                img          = "HuBei_Main_图标_血流",
                headIcon     = "",
                hallName     = "血流成河",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "血流成河",
                gameName     = "ZYXLCH",
                gameId       = 5,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 4,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "红中",
                isOpenUrl    = false,
                wanfaType    = "hbzy_xueliu",
                createName   = "DHHUBEIQP_ZYXLCH_XL",
            },
            {
                img          = "HuBei_Main_图标_十卡五星",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "极速卡五星",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "极速卡五星",
                gameName     = "KWX",
                gameId       = 6,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 5,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "红中",
                isOpenUrl    = false,
                wanfaType    = "hbkwx_xiangyang|hbkwx_xiaogan|hbkwx_suizhou|hbkwx_shiyan",
                createName   = "DHHUBEIQP_KWX_XY|DHHUBEIQP_KWX_XG|DHHUBEIQP_KWX_SZ|DHHUBEIQP_KWX_SY",
                tips         = "襄阳卡五星|孝感卡五星|随州卡五星|十堰卡五星",
            },
            {
                img          = "Public_Electorate_按钮_图标_通用斗地主",
                headIcon     = "Main_入口_斗地主",
                hallName     = "斗地主",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "斗地主",
                gameName     = "DOUDIZHU",
                gameId       = 7,
                isOpen       = true,
                package      = "doudizhu",
                location     = 1,
                showIndex    = 6,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "斗地主",
                isOpenUrl    = false,
                wanfaType    = "0",
                createName   = "DHHUBEIQP_DOUDIZHU_DOUDIZHU",
                tips         = "斗地主",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "飘三叶",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 3,
                name         = "飘三叶",
                gameName     = "ZHAJINHUA",
                gameId       = 8,
                isOpen       = false,
                package      = "zhajinhua",
                location     = 1,
                showIndex    = 7,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "飘三叶",
                isOpenUrl    = false,
                wanfaType    = "0",
                createName   = "DHHUBEIQP_ZHAJINHUA_ZHAJINHUA",
                tips         = "飘三叶",
            },
            {
                img          = "henanmj/module/setplaymodedata/henanmj_setplaymodedatahubei.atlas,HuBei_Main_图标_扑克510k",
                headIcon     = "henanmj/module/setplaymodedata/henanmj_setplaymodedatapublic.atlas,五十K",
                hallName     = "五十K",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "五十K",
                gameName     = "WUSHIK",
                gameId       = 9,
                isOpen       = true,
                package      = "wushik",
                location     = 1,
                showIndex    = 8,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "五十K",
                isOpenUrl    = false,
                wanfaType    = "1|2",
                createName   = "DHHUBEIQP_WUSHIK_WUSHIK",
                tips         = "大冶玩法|黄石玩法",
            }
        },
    },
    {
        id           = 2,
        name         = "大冶市",
        isOpen       = false,
        showIndex    = 2,
        playModeList ={
        },
    },
    {
        id           = 3,
        name         = "黄石市",
        isOpen       = true,
        showIndex    = 3,
        playModeList ={
            {
                img          = "HuBei_Main_图标_晃晃",
                headIcon     = "Main_入口_晃晃",
                hallName     = "黄石晃晃",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "黄石晃晃",
                gameName     = "HSHH",
                gameId       = 301,
                isOpen       = true,
                package      = "majiang",
                location     = 3,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = true,
                coinName     = "红中",
                isOpenUrl    = false,
                playTypeName = "hubei_hshh",
                wanfaType    = "hubei_hshh",
                createName   = "DHHUBEIQP_HSHH_HH",
                goldRoomName         = "黄石晃晃",
                cardTheame   = "2|2|3",
            },
            {
                img          = "Public_Electorate_按钮_图标_字牌通用",
                headIcon     = "Main_入口_样式_01",
                hallName     = "大冶字牌",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "大冶字牌",
                gameName     = "DYZP",
                gameId       = 302,
                isOpen       = true,
                package      = "paohuzi",
                location     = 3,
                showIndex    = 2,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "大冶",
                isOpenUrl    = false,
                wanfaType    = "phz_hubei_dyzp",
                createName   = "DHHUBEIQP_DYZP_DY",
            },
            {
                img          = "henanmj/module/setplaymodedata/henanmj_setplaymodedatahubei.atlas,HuBei_Main_图标_开口番",
                headIcon     = "",
                hallName     = "开口番",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "开口番",
                gameName     = "DYKKF",
                gameId       = 303,
                isOpen       = true,
                package      = "majiang",
                location     = 3,
                showIndex    = 3,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "红中",
                isOpenUrl    = false,
                wanfaType    = "hubei_kkf",
                createName   = "DHHUBEIQP_DYKKF_KKF",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 4,
        name         = "恩施市",
        isOpen       = true,
        showIndex    = 4,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "Main_入口_通用玩法",
                hallName     = "恩施绍胡",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "恩施绍胡",
                gameName     = "ESSH",
                gameId       = 401,
                isOpen       = false,
                package      = "huapai",
                location     = 4,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "恩施绍胡",
                isOpenUrl    = false,
                wanfaType    = "hp_essh",
                createName   = "DHHUBEIQP_ESSH_SH",
                cardTheame   = "2|2|3",
            },
            {
                img          = "henanmj/module/setplaymodedata/henanmj_setplaymodedatahubei.atlas,HuBei_Main_图标_恩施",
                headIcon     = "henanmj/module/setplaymodedata/henanmj_setplaymodedatahubei.atlas,恩施",
                hallName     = "恩施麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "恩施麻将",
                gameName     = "ESMJ",
                gameId       = 402,
                isOpen       = true,
                package      = "majiangshanxi",
                location     = 4,
                showIndex    = 2,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "恩施麻将",
                isOpenUrl    = false,
                wanfaType    = "hbes_ypel|hbes_bpsl",
                createName   = "DHHUBEIQP_ESMJ_YPEL|DHHUBEIQP_ESMJ_BPSL",
                tips         = "一痞二赖|八痞四赖",
            }
        },
    },
    {
        id           = 5,
        name         = "黄冈市",
        isOpen       = true,
        showIndex    = 5,
        playModeList ={
            {
                img          = "henanmj/module/setplaymodedata/henanmj_setplaymodedatahubei.atlas,HuBei_Main_图标_浠水",
                headIcon     = "Main_入口_通用玩法",
                hallName     = "黄冈市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "浠水麻将",
                gameName     = "HGXS",
                gameId       = 501,
                isOpen       = true,
                package      = "majiang",
                location     = 5,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "红中",
                isOpenUrl    = false,
                wanfaType    = "dhhg_xsmj",
                createName   = "DHHUBEIQP_HGXS_XS",
                cardTheame   = "2|2|3",
            }
        },
    }
}
return playModeConfig
