-- 编辑器自动生成，请勿直接修改！
local playModeConfig = {
    {
        id           = 1,
        name         = "大众玩法",
        isOpen       = true,
        showIndex    = 1,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "Main_入口_红中",
                hallName     = "红中麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "红中麻将",
                gameName     = "HZMJ",
                gameId       = 1,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "红中",
                isOpenUrl    = false,
                wanfaType    = "hzmj_v2",
                createName   = "DHHNQP_HZMJ_HZ",
                cardTheame   = "1|1|2",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_极速跑得快",
                hallName     = "跑得快",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "跑得快",
                gameName     = "RUNFAST",
                gameId       = 2,
                isOpen       = true,
                package      = "runfast",
                location     = 1,
                showIndex    = 2,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "跑得快",
                isOpenUrl    = false,
                wanfaType    = "2",
                createName   = "DHHNQP_RUNFAST_RUNFAST",
                tips         = "跑得快",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_拼十",
                hallName     = "拼十",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "拼十",
                gameName     = "BULLFIGHT",
                gameId       = 3,
                isOpen       = false,
                package      = "cowboy",
                location     = 1,
                showIndex    = 3,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "牛仔",
                isOpenUrl    = false,
                playTypeName = "bullfight",
                wanfaType    = "0|1|2|3",
                createName   = "DHHNQP_BULLFIGHT_BF",
                tips         = "轮流坐庄|随机坐庄|看牌抢庄|炸金牛",
            },
            {
                img          = "Public_Electorate_按钮_图标_通用斗地主",
                headIcon     = "Main_入口_斗地主",
                hallName     = "斗地主",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "斗地主",
                gameName     = "DOUDIZHU",
                gameId       = 4,
                isOpen       = true,
                package      = "doudizhu",
                location     = 1,
                showIndex    = 4,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "斗地主",
                isOpenUrl    = false,
                wanfaType    = "0",
                createName   = "DHHNQP_DOUDIZHU_DOUDIZHU",
                tips         = "斗地主",
            },
            {
                img          = "henanmj/module/setplaymodedata/henanmj_setplaymodedatahunan.atlas,HuNan_Main_图标_转转",
                headIcon     = "Main_入口_转转",
                hallName     = "转转麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "转转麻将",
                gameName     = "CSMJZZ",
                gameId       = 5,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 5,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "转转麻将",
                isOpenUrl    = false,
                wanfaType    = "csmj_zhuanzhuan",
                createName   = "DHHNQP_CSMJZZ_ZZ",
                cardTheame   = "1|1|2",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "",
                hallName     = "三公",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "三公",
                gameName     = "SANGONG",
                gameId       = 6,
                isOpen       = false,
                package      = "sangong",
                location     = 1,
                showIndex    = 6,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "",
                isOpenUrl    = false,
                wanfaType    = "1|2",
                createName   = "DHHNQP_SANGONG_SANGONG",
                tips         = "自由下注|自由抢庄",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "飘三叶",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "飘三叶",
                gameName     = "ZHAJINHUA",
                gameId       = 7,
                isOpen       = false,
                package      = "zhajinhua",
                location     = 1,
                showIndex    = 7,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "飘三叶",
                isOpenUrl    = false,
                wanfaType    = "0",
                createName   = "DHHNQP_ZHAJINHUA_ZHAJINHUA",
                tips         = "飘三叶",
            }
        },
    },
    {
        id           = 2,
        name         = "长沙市",
        isOpen       = true,
        showIndex    = 2,
        playModeList ={
            {
                img          = "HuNan_Main_图标_长沙",
                headIcon     = "",
                hallName     = "长沙麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "长沙麻将",
                gameName     = "CSMJCS",
                gameId       = 201,
                isOpen       = true,
                package      = "majiang",
                location     = 2,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "长沙麻将",
                isOpenUrl    = false,
                wanfaType    = "csmj_changsha",
                createName   = "DHHNQP_CSMJCS_CS",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 3,
        name         = "常德市",
        isOpen       = true,
        showIndex    = 3,
        playModeList ={
            {
                img          = "HuNan_Main_图标_常德王",
                headIcon     = "",
                hallName     = "王麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 2,
                name         = "王麻将",
                gameName     = "CDHZ",
                gameId       = 301,
                isOpen       = true,
                package      = "majiang",
                location     = 3,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "红中",
                isOpenUrl    = false,
                wanfaType    = "hnhz_cdhz",
                createName   = "DHHNQP_CDHZ_HZ",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 4,
        name         = "岳阳市",
        isOpen       = true,
        showIndex    = 4,
        playModeList ={
            {
                img          = "HuNan_Main_图标_岳阳",
                headIcon     = "",
                hallName     = "岳阳炒股",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "岳阳炒股",
                gameName     = "YYCG",
                gameId       = 401,
                isOpen       = true,
                package      = "majiang",
                location     = 4,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "红中",
                isOpenUrl    = false,
                wanfaType    = "yymj_yycg",
                createName   = "DHHNQP_YYCG_CG",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 5,
        name         = "湘乡市",
        isOpen       = true,
        showIndex    = 5,
        playModeList ={
            {
                img          = "henanmj/module/setplaymodedata/henanmj_setplaymodedatapublic.atlas,Public_Electorate_按钮_图标_字牌通用",
                headIcon     = "Main_入口_通用玩法",
                hallName     = "湘乡告胡子",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "湘乡告胡子",
                gameName     = "XXZP",
                gameId       = 501,
                isOpen       = true,
                package      = "paohuzi",
                location     = 5,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "红中",
                isOpenUrl    = false,
                wanfaType    = "phz_hunan_xxghz",
                createName   = "DHHNQP_XXZP_XX",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 6,
        name         = "娄底市",
        isOpen       = true,
        showIndex    = 6,
        playModeList ={
            {
                img          = "henanmj/module/setplaymodedata/henanmj_setplaymodedatapublic.atlas,Public_Electorate_按钮_图标_字牌通用",
                headIcon     = "Main_入口_通用玩法",
                hallName     = "娄底放炮罚",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "娄底放炮罚",
                gameName     = "LDZP",
                gameId       = 601,
                isOpen       = true,
                package      = "paohuzi",
                location     = 6,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "红中",
                isOpenUrl    = false,
                wanfaType    = "phz_hunan_ldfpf",
                createName   = "DHHNQP_LDZP_FPF",
                cardTheame   = "1|1|2",
            }
        },
    }
}
return playModeConfig
