-- 编辑器自动生成，请勿直接修改！
local playModeConfig = {
    {
        id           = 1,
        name         = "大众玩法",
        isOpen       = true,
        showIndex    = 1,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "Main_入口_红中",
                hallName     = "红中麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "红中麻将",
                gameName     = "HZMJ",
                gameId       = 1,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "红中",
                isOpenUrl    = false,
                wanfaType    = "hzmj_v2",
                createName   = "DHJXQP_HZMJ_HZ",
                cardTheame   = "0|0|1",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_极速跑得快",
                hallName     = "跑得快",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 1,
                name         = "跑得快",
                gameName     = "RUNFAST",
                gameId       = 3,
                isOpen       = true,
                package      = "runfast",
                location     = 1,
                showIndex    = 2,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "跑得快",
                isOpenUrl    = false,
                wanfaType    = "2",
                createName   = "DHJXQP_RUNFAST_RUNFAST",
                tips         = "经典玩法",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_拼十",
                hallName     = "拼十",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 0,
                name         = "拼十",
                gameName     = "BULLFIGHT",
                gameId       = 4,
                isOpen       = false,
                package      = "cowboy",
                location     = 1,
                showIndex    = 3,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "牛仔",
                isOpenUrl    = false,
                playTypeName = "bullfight",
                wanfaType    = "0|1|2|3",
                createName   = "DHJXQP_BULLFIGHT_BF",
                tips         = "轮流坐庄|随机坐庄|看牌抢庄|炸金牛",
            },
            {
                img          = "Public_Electorate_按钮_图标_通用斗地主",
                headIcon     = "Main_入口_斗地主",
                hallName     = "斗地主",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "斗地主",
                gameName     = "DOUDIZHU",
                gameId       = 7,
                isOpen       = true,
                package      = "doudizhu",
                location     = 1,
                showIndex    = 4,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "斗地主",
                isOpenUrl    = false,
                wanfaType    = "0",
                createName   = "DHJXQP_DOUDIZHU_DOUDIZHU",
                tips         = "斗地主",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "飘三叶",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 0,
                name         = "飘三叶",
                gameName     = "ZHAJINHUA",
                gameId       = 6,
                isOpen       = false,
                package      = "zhajinhua",
                location     = 1,
                showIndex    = 5,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "飘三叶",
                isOpenUrl    = false,
                wanfaType    = "0",
                createName   = "DHJXQP_ZHAJINHUA_ZHAJINHUA",
                tips         = "飘三叶",
            },
            {
                img          = "henanmj/module/setplaymodedata/henanmj_setplaymodedatahunan.atlas,HuNan_Main_图标_转转",
                headIcon     = "Main_入口_通用玩法",
                hallName     = "转转麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "转转麻将",
                gameName     = "ZZMJ",
                gameId       = 8,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 6,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "红中",
                isOpenUrl    = false,
                wanfaType    = "csmj_zhuanzhuan",
                createName   = "DHJXQP_ZZMJ_ZZ",
                cardTheame   = "1|1|2",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "十三张",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "十三张",
                gameName     = "SHISANZHANG",
                gameId       = 9,
                isOpen       = false,
                package      = "shisanzhang",
                location     = 1,
                showIndex    = 7,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "",
                isOpenUrl    = false,
                wanfaType    = "0",
                createName   = "DHJXQP_SHISANZHANG_SSZ",
            }
        },
    },
    {
        id           = 2,
        name         = "九江市",
        isOpen       = true,
        showIndex    = 2,
        playModeList ={
            {
                img          = "henanmj/module/setplaymodedata/henanmj_setplaymodedatajiangxi.atlas,JiangXi_Main_图标_湖口",
                headIcon     = "Main_入口_通用玩法",
                hallName     = "湖口麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "湖口麻将",
                gameName     = "JJHK",
                gameId       = 201,
                isOpen       = true,
                package      = "majiang",
                location     = 2,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "红中",
                isOpenUrl    = false,
                wanfaType    = "jxqp_jjhk",
                createName   = "DHJXQP_JJHK_HK",
                cardTheame   = "1|1|2",
            }
        },
    }
}
return playModeConfig
