-- 编辑器自动生成，请勿直接修改！
local playModeConfig = {
    {
        id           = 1,
        name         = "大众玩法",
        isOpen       = true,
        showIndex    = 1,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_拼十",
                hallName     = "拼十",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 3,
                name         = "拼十",
                gameName     = "BULLFIGHT",
                gameId       = 1,
                isOpen       = false,
                package      = "cowboy",
                location     = 1,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "拼十",
                isOpenUrl    = false,
                playTypeName = "bullfight",
                wanfaType    = "0|1|2",
                createName   = "DHSHXQP_BULLFIGHT_BF",
                tips         = "轮流坐庄|随机坐庄|看牌抢庄",
            },
            {
                img          = "Public_Electorate_按钮_图标_通用斗地主",
                headIcon     = "Main_入口_斗地主",
                hallName     = "斗地主",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "斗地主",
                gameName     = "DOUDIZHU",
                gameId       = 2,
                isOpen       = true,
                package      = "doudizhu",
                location     = 1,
                showIndex    = 2,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "斗地主",
                isOpenUrl    = false,
                wanfaType    = "0",
                createName   = "DHSHXQP_DOUDIZHU_DOUDIZHU",
                tips         = "斗地主",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_极速跑得快",
                hallName     = "跑得快",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "跑得快",
                gameName     = "RUNFAST",
                gameId       = 3,
                isOpen       = true,
                package      = "runfast",
                location     = 1,
                showIndex    = 3,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "跑得快",
                isOpenUrl    = false,
                wanfaType    = "2",
                createName   = "DHSHXQP_RUNFAST_RUNFAST",
                tips         = "跑得快",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "飘三叶",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 3,
                name         = "飘三叶",
                gameName     = "ZHAJINHUA",
                gameId       = 4,
                isOpen       = false,
                package      = "zhajinhua",
                location     = 1,
                showIndex    = 4,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "飘三叶",
                isOpenUrl    = false,
                wanfaType    = "0",
                createName   = "DHSHXQP_ZHAJINHUA_ZHAJINHUA",
                tips         = "飘三叶",
            }
        },
    },
    {
        id           = 2,
        name         = "吕梁市",
        isOpen       = true,
        showIndex    = 2,
        playModeList ={
            {
                img          = "henanmj/module/setplaymodedata/henanmj_setplaymodedatashanxi.atlas,ShanXi_Main_图标_抠点",
                headIcon     = "Main_入口_通用玩法",
                hallName     = "吕梁抠点",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "吕梁抠点",
                gameName     = "KDDMJ",
                gameId       = 201,
                isOpen       = true,
                package      = "majiangshanxi",
                location     = 2,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "吕梁抠点",
                isOpenUrl    = false,
                wanfaType    = "majiangshanxi_shanxi_llkdd",
                createName   = "DHSHXQP_KDDMJ_KDD",
                cardTheame   = "1|1|2",
            }
        },
    }
}
return playModeConfig
