-- 编辑器自动生成，请勿直接修改！
local playModeConfig = {
    {
        id           = 1,
        name         = "大众玩法",
        isOpen       = true,
        showIndex    = 1,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_极速跑得快",
                hallName     = "跑得快",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "跑得快",
                gameName     = "RUNFAST",
                gameId       = 1,
                isOpen       = true,
                package      = "runfast",
                location     = 1,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "跑得快",
                isOpenUrl    = false,
                wanfaType    = "2",
                createName   = "DHYNQP_RUNFAST_RUNFAST",
                tips         = "跑得快",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_拼十",
                hallName     = "拼十",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "拼十",
                gameName     = "BULLFIGHT",
                gameId       = 2,
                isOpen       = false,
                package      = "cowboy",
                location     = 1,
                showIndex    = 2,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "牛仔",
                isOpenUrl    = false,
                playTypeName = "bullfight",
                wanfaType    = "0|1|2|3",
                createName   = "DHYNQP_BULLFIGHT_BF",
                tips         = "轮流坐庄|随机坐庄|看牌抢庄|炸金牛",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "叼三批",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "叼三批",
                gameName     = "ZHAJINHUA",
                gameId       = 4,
                isOpen       = false,
                package      = "zhajinhua",
                location     = 1,
                showIndex    = 3,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "叼三批",
                isOpenUrl    = false,
                wanfaType    = "0",
                createName   = "DHYNQP_ZHAJINHUA_ZHAJINHUA",
                tips         = "叼三批",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "捞腌菜",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "捞腌菜",
                gameName     = "LAOYANCAI",
                gameId       = 3,
                isOpen       = false,
                package      = "laoyancai",
                location     = 1,
                showIndex    = 4,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "捞腌菜",
                isOpenUrl    = false,
                wanfaType    = "0|1",
                createName   = "DHYNQP_LAOYANCAI_LAOYANCAI",
                tips         = "经典玩法|码宝轮庄",
            },
            {
                img          = "Public_Electorate_按钮_图标_通用斗地主",
                headIcon     = "Main_入口_斗地主",
                hallName     = "斗地主",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "斗地主",
                gameName     = "DOUDIZHU",
                gameId       = 5,
                isOpen       = true,
                package      = "doudizhu",
                location     = 1,
                showIndex    = 5,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "斗地主",
                isOpenUrl    = false,
                wanfaType    = "0",
                createName   = "DHYNQP_DOUDIZHU_DOUDIZHU",
                tips         = "斗地主",
            }
        },
    },
    {
        id           = 2,
        name         = "文山州",
        isOpen       = true,
        showIndex    = 2,
        playModeList ={
            {
                img          = "YunNan_Main_图标_山",
                headIcon     = "",
                hallName     = "文山州",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "砚山麻将",
                gameName     = "WSZMJ",
                gameId       = 201,
                isOpen       = true,
                package      = "majiang",
                location     = 2,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "文山州",
                isOpenUrl    = false,
                wanfaType    = "ynwsz_yanshan",
                createName   = "DHYNQP_WSZMJ_YS",
                cardTheame   = "0|0|1",
            }
        },
    },
    {
        id           = 3,
        name         = "曲靖市",
        isOpen       = true,
        showIndex    = 3,
        playModeList ={
            {
                img          = "YunNan_Main_图标_曲靖飞小鸡",
                headIcon     = "Main_入口_飞小鸡",
                hallName     = "飞小鸡",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "飞小鸡",
                gameName     = "QJMJFXJ",
                gameId       = 301,
                isOpen       = true,
                package      = "majiang",
                location     = 3,
                showIndex    = 1,
                color        = 1,
                isOnline     = true,
                isOpenGold   = false,
                coinName     = "飞小鸡",
                isOpenUrl    = false,
                wanfaType    = "ynqj_feixiaoji",
                createName   = "DHYNQP_QJMJFXJ_FXJ",
                cardTheame   = "1|1|2",
            }
        },
    }
}
return playModeConfig
